In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/data.csv")

In [3]:
df.head()

,R_fighter,B_fighter,Referee,date,location,Winner,title_bout,weight_class,no_of_rounds,B_current_lose_streak,...,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_wins,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
0,Henry Cejudo,Marlon Moraes,Marc Goddard,2019-06-08,"Chicago, Illinois, USA",Red,True,Bantamweight,5,0.0,...,2.0,0.0,0.0,8.0,Orthodox,162.56,162.56,135.0,31.0,32.0
1,Valentina Shevchenko,Jessica Eye,Robert Madrigal,2019-06-08,"Chicago, Illinois, USA",Red,True,Women's Flyweight,5,0.0,...,0.0,2.0,0.0,5.0,Southpaw,165.10,167.64,125.0,32.0,31.0
2,Tony Ferguson,Donald Cerrone,Dan Miragliotta,2019-06-08,"Chicago, Illinois, USA",Red,False,Lightweight,3,0.0,...,3.0,6.0,1.0,14.0,Orthodox,180.34,193.04,155.0,36.0,35.0
3,Jimmie Rivera,Petr Yan,Kevin MacDonald,2019-06-08,"Chicago, Illinois, USA",Blue,False,Bantamweight,3,0.0,...,1.0,0.0,0.0,6.0,Orthodox,162.56,172.72,135.0,26.0,29.0
4,Tai Tuivasa,Blagoy Ivanov,Dan Miragliotta,2019-06-08,"Chicago, Illinois, USA",Blue,False,Heavyweight,3,0.0,...,2.0,0.0,0.0,3.0,Southpaw,187.96,190.50,264.0,32.0,26.0

# Replace small num of missing vals
## R / B Height = 12 vals
## R / B Weight = 9 vals

In [4]:
df[df["R_Height_cms"].isnull()]

,R_fighter,B_fighter,Referee,date,location,Winner,title_bout,weight_class,no_of_rounds,B_current_lose_streak,...,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_wins,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
103,Kennedy Nzechukwu,Paul Craig,Keith Peterson,2019-03-30,"Philadelphia, Pennsylvania, USA",Blue,False,Light Heavyweight,3,1.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,31.0,NaN
3607,Tom Blackledge,Anthony Perosh,John Sharp,2011-02-26,"Sydney, New South Wales, Australia",Blue,False,Light Heavyweight,3,3.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,205.0,38.0,NaN
5029,Jack Nilson,Saeed Hosseini,Joe Hamilton,1997-05-30,"Augusta, Georgia, USA",Red,False,Lightweight,2,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
5132,Frank Hamaker,Thaddeus Luster,John McCarthy,1994-03-11,"Denver, Colorado, USA",Red,False,Open Weight,1,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.at[103,"R_Height_cms"] = 195.58
df.at[3607,"R_Height_cms"] = 182.88
df.at[5029,"R_Height_cms"] = 176.48
df.at[5132,"R_Height_cms"] = 187.96

In [17]:
df[df["B_Height_cms"].isnull()]

,R_fighter,B_fighter,Referee,date,location,Winner,title_bout,weight_class,no_of_rounds,B_current_lose_streak,...,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_wins,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
3402,Terry Etim,Edward Faaloloto,Leon Roberts,2011-11-05,"Birmingham, England, United Kingdom",Red,False,Lightweight,3,1.0,...,1.0,3.0,0.0,5.0,Orthodox,185.42,185.42,155.0,27.0,25.0
3518,Michael Johnson,Edward Faaloloto,Mark Matheny,2011-06-26,"Pittsburgh, Pennsylvania, USA",Red,False,Lightweight,3,0.0,...,0.0,0.0,0.0,0.0,Southpaw,177.80,185.42,145.0,26.0,25.0
4978,Laverne Clark,Frank Caracci,Tony Mullinax,1999-01-08,"New Orleans, Louisiana, USA",Red,False,Lightweight,2,0.0,...,0.0,0.0,0.0,0.0,Orthodox,180.34,NaN,170.0,NaN,25.0
4992,Chuck Liddell,Noe Hernandez,Joe Hamilton,1998-05-15,"Mobile, Alabama, USA",Red,False,Middleweight,1,0.0,...,0.0,0.0,0.0,0.0,Orthodox,187.96,193.04,205.0,NaN,28.0
5020,Alex Hunter,Sam Fulton,Joe Hamilton,1997-07-27,"Birmingham, Alabama, USA",Red,False,Heavyweight,2,0.0,...,0.0,0.0,0.0,0.0,Orthodox,175.26,NaN,226.0,NaN,NaN
5029,Jack Nilson,Saeed Hosseini,Joe Hamilton,1997-05-30,"Augusta, Georgia, USA",Red,False,Lightweight,2,0.0,...,0.0,0.0,0.0,0.0,NaN,176.48,NaN,NaN,NaN,NaN
5116,Ken Shamrock,Felix Lee Mitchell,John McCarthy,1994-09-09,"Charlotte, North Carolina, USA",Red,False,Open Weight,1,0.0,...,1.0,1.0,0.0,2.0,Orthodox,185.42,182.88,205.0,NaN,30.0
5134,Patrick Smith,Ray Wizard,John McCarthy,1994-03-11,"Denver, Colorado, USA",Red,False,Open Weight,1,0.0,...,0.0,0.0,0.0,0.0,Orthodox,187.96,NaN,225.0,NaN,30.0

In [21]:
df.at[3402,"B_Height_cms"] = 175.26
df.at[3518,"B_Height_cms"] = 175.26
df.at[4978,"B_Height_cms"] = 170.18 
df.at[4992,"B_Height_cms"] = 184.11
df.at[5020,"B_Height_cms"] = 187.96
df.at[5029,"B_Height_cms"] = 176.60
df.at[5116,"B_Height_cms"] = 180.00
df.at[5134,"B_Height_cms"] = 184.91

In [23]:
df[df["R_Weight_lbs"].isnull()]

,R_fighter,B_fighter,Referee,date,location,Winner,title_bout,weight_class,no_of_rounds,B_current_lose_streak,...,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_wins,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
103,Kennedy Nzechukwu,Paul Craig,Keith Peterson,2019-03-30,"Philadelphia, Pennsylvania, USA",Blue,False,Light Heavyweight,3,1.0,...,0.0,0.0,0.0,0.0,NaN,195.58,NaN,NaN,31.0,NaN
5029,Jack Nilson,Saeed Hosseini,Joe Hamilton,1997-05-30,"Augusta, Georgia, USA",Red,False,Lightweight,2,0.0,...,0.0,0.0,0.0,0.0,NaN,176.48,NaN,NaN,NaN,NaN
5132,Frank Hamaker,Thaddeus Luster,John McCarthy,1994-03-11,"Denver, Colorado, USA",Red,False,Open Weight,1,0.0,...,0.0,0.0,0.0,0.0,NaN,187.96,NaN,NaN,NaN,NaN

In [28]:
df.at[103,"R_Weight_lbs"] = 205
df.at[5029,"R_Weight_lbs"] = 155.99
df.at[5132,"R_Weight_lbs"] = 224.52

In [29]:
df[df["B_Weight_lbs"].isnull()]

,R_fighter,B_fighter,Referee,date,location,Winner,title_bout,weight_class,no_of_rounds,B_current_lose_streak,...,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_wins,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
4978,Laverne Clark,Frank Caracci,Tony Mullinax,1999-01-08,"New Orleans, Louisiana, USA",Red,False,Lightweight,2,0.0,...,0.0,0.0,0.0,0.0,Orthodox,180.34,NaN,170.00,NaN,25.0
4992,Chuck Liddell,Noe Hernandez,Joe Hamilton,1998-05-15,"Mobile, Alabama, USA",Red,False,Middleweight,1,0.0,...,0.0,0.0,0.0,0.0,Orthodox,187.96,193.04,205.00,NaN,28.0
5020,Alex Hunter,Sam Fulton,Joe Hamilton,1997-07-27,"Birmingham, Alabama, USA",Red,False,Heavyweight,2,0.0,...,0.0,0.0,0.0,0.0,Orthodox,175.26,NaN,226.00,NaN,NaN
5029,Jack Nilson,Saeed Hosseini,Joe Hamilton,1997-05-30,"Augusta, Georgia, USA",Red,False,Lightweight,2,0.0,...,0.0,0.0,0.0,0.0,NaN,176.48,NaN,155.99,NaN,NaN
5116,Ken Shamrock,Felix Lee Mitchell,John McCarthy,1994-09-09,"Charlotte, North Carolina, USA",Red,False,Open Weight,1,0.0,...,1.0,1.0,0.0,2.0,Orthodox,185.42,182.88,205.00,NaN,30.0
5134,Patrick Smith,Ray Wizard,John McCarthy,1994-03-11,"Denver, Colorado, USA",Red,False,Open Weight,1,0.0,...,0.0,0.0,0.0,0.0,Orthodox,187.96,NaN,225.00,NaN,30.0

In [33]:
df.at[4978,"B_Weight_lbs"] = 200
df.at[4992,"B_Weight_lbs"] = 184.72
df.at[5020,"B_Weight_lbs"] = 250
df.at[5029,"B_Weight_lbs"] = 265
df.at[5116,"B_Weight_lbs"] = 224.52
df.at[5134,"B_Weight_lbs"] = 224.52

In [44]:
df.to_csv("updated_data.csv",index=False)

In [34]:
#mean calc
#df[df["weight_class"]=="Open Weight"]["R_Weight_lbs"].mean()

In [52]:
#check vals
new = pd.read_csv("data/updated_data.csv")
new[new["R_Weight_lbs"].isnull()]

Empty DataFrame
Columns: [R_fighter, B_fighter, Referee, date, location, Winner, title_bout, weight_class, no_of_rounds, B_current_lose_streak, B_current_win_streak, B_draw, B_avg_BODY_att, B_avg_BODY_landed, B_avg_CLINCH_att, B_avg_CLINCH_landed, B_avg_DISTANCE_att, B_avg_DISTANCE_landed, B_avg_GROUND_att, B_avg_GROUND_landed, B_avg_HEAD_att, B_avg_HEAD_landed, B_avg_KD, B_avg_LEG_att, B_avg_LEG_landed, B_avg_PASS, B_avg_REV, B_avg_SIG_STR_att, B_avg_SIG_STR_landed, B_avg_SIG_STR_pct, B_avg_SUB_ATT, B_avg_TD_att, B_avg_TD_landed, B_avg_TD_pct, B_avg_TOTAL_STR_att, B_avg_TOTAL_STR_landed, B_longest_win_streak, B_losses, B_avg_opp_BODY_att, B_avg_opp_BODY_landed, B_avg_opp_CLINCH_att, B_avg_opp_CLINCH_landed, B_avg_opp_DISTANCE_att, B_avg_opp_DISTANCE_landed, B_avg_opp_GROUND_att, B_avg_opp_GROUND_landed, B_avg_opp_HEAD_att, B_avg_opp_HEAD_landed, B_avg_opp_KD, B_avg_opp_LEG_att, B_avg_opp_LEG_landed, B_avg_opp_PASS, B_avg_opp_REV, B_avg_opp_SIG_STR_att, B_avg_opp_SIG_STR_landed, B_avg_opp_SIG_STR_pct, B_avg_opp_SUB_ATT, B_avg_opp_TD_att, B_avg_opp_TD_landed, B_avg_opp_TD_pct, B_avg_opp_TOTAL_STR_att, B_avg_opp_TOTAL_STR_landed, B_total_rounds_fought, B_total_time_fought(seconds), B_total_title_bouts, B_win_by_Decision_Majority, B_win_by_Decision_Split, B_win_by_Decision_Unanimous, B_win_by_KO/TKO, B_win_by_Submission, B_win_by_TKO_Doctor_Stoppage, B_wins, B_Stance, B_Height_cms, B_Reach_cms, B_Weight_lbs, R_current_lose_streak, R_current_win_streak, R_draw, R_avg_BODY_att, R_avg_BODY_landed, R_avg_CLINCH_att, R_avg_CLINCH_landed, R_avg_DISTANCE_att, R_avg_DISTANCE_landed, R_avg_GROUND_att, R_avg_GROUND_landed, R_avg_HEAD_att, R_avg_HEAD_landed, R_avg_KD, R_avg_LEG_att, R_avg_LEG_landed, R_avg_PASS, R_avg_REV, R_avg_SIG_STR_att, R_avg_SIG_STR_landed, R_avg_SIG_STR_pct, R_avg_SUB_ATT, R_avg_TD_att, R_avg_TD_landed, ...]
Index: []

[0 rows x 145 columns]